name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is master
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /opt/stock_ticker_generator
          ./deployment/deploy_from_git.sh


